import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:health_app/di.dart';
import 'package:health_app/features/auth/data/responses/user/user_response.dart';

// This file will be generated by riverpod_generator
part 'change_password_provider.g.dart';

@riverpod
class ChangePassword extends _$ChangePassword {
  @override
  FutureOr<void> build() {
    // Initial state is idle (null)
  }

  Future<bool> submit({
    required String currentPassword,
    required String newPassword,
    required String confirmPassword,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final res = await getDio.post(
        '/auth/change-password',
        data: {
          'currentPassword': currentPassword,
          'newPassword': newPassword,
          'confirmNewPassword': confirmPassword,
        },
      );

      final response = GeneralResponse.fromJson(res.data);
      if (!response.wasSuccesfull) {
        throw response.message ?? 'Unknown Error';
      }
    });

    return !state.hasError;
  }
}
